version: '3.4'

services:
  arcus.messaging.tests.workers.servicebus.queue:
    image: arcusazure/arcus.messaging.tests.workers.servicebus.queue
    build:
      context: .
      dockerfile: Arcus.Messaging.Tests.Workers.ServiceBus.Queue/Dockerfile
  arcus.messaging.tests.workers.servicebus.topic:
    image: arcusazure/arcus.messaging.tests.workers.servicebus.topic
    build:
      context: .
      dockerfile: Arcus.Messaging.Tests.Workers.ServiceBus.Topic/Dockerfile
  arcus.messaging.tests.runtimes.azurefunction.servicebus.queue:
    image: arcusazure/arcus.messaging.tests.runtimes.azurefunction.servicebus.queue
    build:
      context: .
      dockerfile: Arcus.Messaging.Tests.Runtimes.AzureFunction.ServiceBus.Queue/Dockerfile